#pragma once

#include <oxenc/base64.h>

// Encoded images for formats the tests cannot make themselves: our libvips has no HEVC or AV1
// encoder.

namespace image_fixtures {

using namespace oxenc::literals;

// 64x48, from `vips heifsave --compression hevc` (libheif with x265).
inline constexpr auto heic_64x48 =
        "AAAAHGZ0eXBoZWljAAAAAG1pZjFoZWljbWlhZgAAAaptZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAA"
        "AAAAAAAAAAAAADRpbG9jAAAAAERAAAIAAQAAAAABzgABAAAAAAAAABYAAgAAAAAB5AABAAAAAAAAAL4AAAA4aWlu"
        "ZgAAAAAAAgAAABVpbmZlAgAAAAABAABodmMxAAAAABVpbmZlAgAAAQACAABFeGlmAAAAAA5waXRtAAAAAAABAAAA"
        "6WlwcnAAAADKaXBjbwAAAHZodmNDAQNwAAAAAAAAAAAAHvAA/P34+AAADwNgAAEAGEABDAH//wNwAAADAJAAAAMA"
        "AAMAHroCQGEAAQAqQgEBA3AAAAMAkAAAAwAAAwAeoCCBBZbq5Ka5uAhoMCAAAAMDIAAAAwAhYgABAAZEAcFzwIkA"
        "AAAUaXNwZQAAAAAAAABAAAAAQAAAAChjbGFwAAAAQAAAAAEAAAAwAAAAAQAAAAAAAAAC////8AAAAAIAAAAQcGl4"
        "aQAAAAADCAgIAAAAF2lwbWEAAAAAAAAAAQABBIECBIMAAAAaaXJlZgAAAAAAAAAOY2RzYwACAAEAAQAAANxtZGF0"
        "AAAAEigBrxOA+FDQp//+MofGYpU1eAAAAAZFeGlmAABJSSoACAAAAAYAEgEDAAEAAAABAAAAGgEFAAEAAABWAAAA"
        "GwEFAAEAAABeAAAAKAEDAAEAAAACAAAAEwIDAAEAAAABAAAAaYcEAAEAAABmAAAAAAAAADhjAADoAwAAOGMAAOgD"
        "AAAGAACQBwAEAAAAMDIxMAGRBwAEAAAAAQIDAACgBwAEAAAAMDEwMAGgAwABAAAA//8AAAKgBAABAAAAQAAAAAOg"
        "BAABAAAAMAAAAAAAAAA="_b64_b;

// 64x48, from ffmpeg with libaom-av1.
inline constexpr auto avif_64x48 =
        "AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAAD5bWV0YQAAAAAAAAAvaGRscgAAAAAAAAAAcGljdAAA"
        "AAAAAAAAAAAAAFBpY3R1cmVIYW5kbGVyAAAAAA5waXRtAAAAAAABAAAAHmlsb2MAAAAARAAAAQABAAAAAQAAASEA"
        "AAAWAAAAKGlpbmYAAAAAAAEAAAAaaW5mZQIAAAAAAQAAYXYwMUNvbG9yAAAAAGppcHJwAAAAS2lwY28AAAAUaXNw"
        "ZQAAAAAAAABAAAAAMAAAABBwaXhpAAAAAAMICAgAAAAMYXYxQ4EADAAAAAATY29scm5jbHgAAgACAAIAAAAAF2lw"
        "bWEAAAAAAAAAAQABBAECgwQAAAAebWRhdAoGGBV/vbAIMgwaAAAAUAAAAAoFfNg="_b64_b;

}  // namespace image_fixtures
