#pragma once

#include <oxenc/base64.h>

// Encoded images for formats the tests cannot make themselves: our libvips has no HEVC or AV1
// encoder.

namespace image_fixtures {

using namespace oxenc::literals;

// 64x48, from `vips heifsave --compression hevc` (libheif with x265).
inline constexpr auto heic_64x48 =
        "AAAAHGZ0eXBoZWljAAAAAG1pZjFoZWljbWlhZgAAAaptZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAA"
        "AAAAAAAAAAAAADRpbG9jAAAAAERAAAIAAQAAAAABzgABAAAAAAAAABYAAgAAAAAB5AABAAAAAAAAAL4AAAA4aWlu"
        "ZgAAAAAAAgAAABVpbmZlAgAAAAABAABodmMxAAAAABVpbmZlAgAAAQACAABFeGlmAAAAAA5waXRtAAAAAAABAAAA"
        "6WlwcnAAAADKaXBjbwAAAHZodmNDAQNwAAAAAAAAAAAAHvAA/P34+AAADwNgAAEAGEABDAH//wNwAAADAJAAAAMA"
        "AAMAHroCQGEAAQAqQgEBA3AAAAMAkAAAAwAAAwAeoCCBBZbq5Ka5uAhoMCAAAAMDIAAAAwAhYgABAAZEAcFzwIkA"
        "AAAUaXNwZQAAAAAAAABAAAAAQAAAAChjbGFwAAAAQAAAAAEAAAAwAAAAAQAAAAAAAAAC////8AAAAAIAAAAQcGl4"
        "aQAAAAADCAgIAAAAF2lwbWEAAAAAAAAAAQABBIECBIMAAAAaaXJlZgAAAAAAAAAOY2RzYwACAAEAAQAAANxtZGF0"
        "AAAAEigBrxOA+FDQp//+MofGYpU1eAAAAAZFeGlmAABJSSoACAAAAAYAEgEDAAEAAAABAAAAGgEFAAEAAABWAAAA"
        "GwEFAAEAAABeAAAAKAEDAAEAAAACAAAAEwIDAAEAAAABAAAAaYcEAAEAAABmAAAAAAAAADhjAADoAwAAOGMAAOgD"
        "AAAGAACQBwAEAAAAMDIxMAGRBwAEAAAAAQIDAACgBwAEAAAAMDEwMAGgAwABAAAA//8AAAKgBAABAAAAQAAAAAOg"
        "BAABAAAAMAAAAAAAAAA="_b64_b;

// Stored 64x48 as quadrants of sRGB red and green over blue and white, drawn in Display P3 and
// encoded by ImageIO, which marks a quarter turn clockwise as both irot and EXIF orientation 6.
inline constexpr auto heic_p3_rotated =
        "AAAAJGZ0eXBoZWljAAAAAG1pZjFNaVBybWlhZk1pSEJoZWljAAAD1G1ldGEAAAAAAAAAIWhkbHIAAAAAAAAAAHBpY3"
        "QAAAAAAAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAADnBpdG0AAAAAAAEAAAA4"
        "aWluZgAAAAAAAgAAABVpbmZlAgAAAAABAABodmMxAAAAABVpbmZlAgAAAQACAABFeGlmAAAAABppcmVmAAAAAAAAAA"
        "5jZHNjAAIAAQABAAAC92lwcnAAAALWaXBjbwAAAiRjb2xycHJvZgAAAhhhcHBsBAAAAG1udHJSR0IgWFlaIAfmAAEA"
        "AQAAAAAAAGFjc3BBUFBMAAAAAEFQUEwAAAAAAAAAAAAAAAAAAAAAAAD21gABAAAAANMtYXBwbOz9o444hUfDbbS9T3"
        "raGC8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACmRlc2MAAAD8AAAAMGNwcnQAAAEsAAAAUHd0cHQAAAF8"
        "AAAAFHJYWVoAAAGQAAAAFGdYWVoAAAGkAAAAFGJYWVoAAAG4AAAAFHJUUkMAAAHMAAAAIGNoYWQAAAHsAAAALGJUUk"
        "MAAAHMAAAAIGdUUkMAAAHMAAAAIG1sdWMAAAAAAAAAAQAAAAxlblVTAAAAFAAAABwARABpAHMAcABsAGEAeQAgAFAA"
        "M21sdWMAAAAAAAAAAQAAAAxlblVTAAAANAAAABwAQwBvAHAAeQByAGkAZwBoAHQAIABBAHAAcABsAGUAIABJAG4AYw"
        "AuACwAIAAyADAAMgAyWFlaIAAAAAAAAPbVAAEAAAAA0yxYWVogAAAAAAAAg98AAD2/////u1hZWiAAAAAAAABKvwAA"
        "sTcAAAq5WFlaIAAAAAAAACg4AAARCwAAyLlwYXJhAAAAAAADAAAAAmZmAADypwAADVkAABPQAAAKW3NmMzIAAAAAAA"
        "EMQgAABd7///MmAAAHkwAA/ZD///ui///9owAAA9wAAMBuAAAADGNsbGkAywBAAAAAFGlzcGUAAAAAAAAAQAAAADAA"
        "AAAJaXJvdAMAAAAQcGl4aQAAAAADCAgIAAAAcWh2Y0MBA3AAAACwAAAAAAAe8AD8/fj4AAALA6AAAQAXQAEMAf//A3"
        "AAAAMAsAAAAwAAAwAecCShAAEAI0IBAQNwAAADALAAAAMAAAMAHqAUIEHBjE4h7kWVTcCAgYAgogABAAlEAcBghLIR"
        "FNkAAAAZaXBtYQAAAAAAAAABAAEGgQIDhAWGAAAALGlsb2MAAAAARAAAAgABAAAAAQAABCwAAABbAAIAAAABAAAECA"
        "AAACQAAAABbWRhdAAAAAAAAACPAAAABkV4aWYAAE1NACoAAAAIAAEBEgADAAAAAQAGAAAAAAAAAAAAVygBr6PJgDvV"
        "ifGk//9OfofUHW+7x6tnouv6aBS99N/+e9mqpgR4Ib8s//+dXf+6MhL/wG/q9q+BsrvOdKdV1zpbaL2z+9iL/52cl+"
        "8DVVOuVhlvVHnVkA=="_b64_b;
// 64x48, from ffmpeg with libaom-av1.
inline constexpr auto avif_64x48 =
        "AAAAIGZ0eXBhdmlmAAAAAGF2aWZtaWYxbWlhZk1BMUIAAAD5bWV0YQAAAAAAAAAvaGRscgAAAAAAAAAAcGljdAAA"
        "AAAAAAAAAAAAAFBpY3R1cmVIYW5kbGVyAAAAAA5waXRtAAAAAAABAAAAHmlsb2MAAAAARAAAAQABAAAAAQAAASEA"
        "AAAWAAAAKGlpbmYAAAAAAAEAAAAaaW5mZQIAAAAAAQAAYXYwMUNvbG9yAAAAAGppcHJwAAAAS2lwY28AAAAUaXNw"
        "ZQAAAAAAAABAAAAAMAAAABBwaXhpAAAAAAMICAgAAAAMYXYxQ4EADAAAAAATY29scm5jbHgAAgACAAIAAAAAF2lw"
        "bWEAAAAAAAAAAQABBAECgwQAAAAebWRhdAoGGBV/vbAIMgwaAAAAUAAAAAoFfNg="_b64_b;

}  // namespace image_fixtures
